specVersion: 1.0.0
name: subql_bifrost_for_vfil
version: 1.0.0
runner:
  node:
    name: "@subql/node"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: For Bifrost vFil project
repository: https://github.com/subquery/bifrost-subql-starter
schema:
  file: ./schema.graphql
network:
  # test ws://172.19.64.5:9866
  endpoint: ws://172.19.0.34:29944
  genesisHash: '0x262e1b2ad728475fd6fe88e62d34c200abe6fd693931ddad144059b1eb884e5b'
  dictionary: https://api.subquery.network/sq/subquery/bifrost-parachain-dictionary
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1981753
    mapping:
      file: ./dist/index.js
      handlers:
      # VtokenMinting module handlers
        - handler: handleVtokenMintingMinted
          kind: substrate/EventHandler
          filter:
            module: vtokenMinting
            method: Minted
        - handler: handleVtokenMintingRedeemed
          kind: substrate/EventHandler
          filter:
            module: vtokenMinting
            method: Redeemed
      # SLP module handlers
        - handler: handleSlpRefund
          kind: substrate/EventHandler
          filter:
            module: slp
            method: Refund
        - handler: handleSlpTransferTo
          kind: substrate/EventHandler
          filter:
            module: slp
            method: TransferTo
      # CrossInOut module handlers
        - handler: handleCrossInOutCrossedIn
          kind: substrate/EventHandler
          filter:
            module: crossInOut
            method: CrossedIn
        - handler: handleCrossInOutCrossedOut
          kind: substrate/EventHandler
          filter:
            module: crossInOut
            method: CrossedOut
        - handler: handleCrossInOutLinkedAccountRegistered
          kind: substrate/EventHandler
          filter:
            module: crossInOut
            method: LinkedAccountRegistered
